# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

development:
  ADMIN_NAME: "Samuel"
  ADMIN_EMAIL: "bouaroua.samuel@gmail.com"
  ADMIN_PASSWORD: "821000"
  GMAIL_USERNAME: "bouaroua.samuel@gmail.com"
  EMAIL_USERNAME: "contact@pssgrs.com"
  GMAIL_PASSWORD: "mhesmueigfewbrhm"
  EMAIL_PASSWORD: "lapapayeverte46*"
  GMAPS_API_KEY: "AIzaSyD8u5Q-Ih61ySje3OtuWDLyWOkMXTo6qJ8"
  GMAPSJS_API_KEY: "AIzaSyAFqXx9fhhwbUddVLwIF9JJNEcWC5lc5Ys"
  AWS_ACCESS_KEY_ID: "AKIAIQHL7MWX4WWKECWA"
  AWS_SECRET_ACCESS_KEY: "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"
  S3_BUCKET: "lespassagers"
  S3_REGION: "eu-west-1"
  FB_APPID: "2709710669054884"
  TW_APPID: "@pssgrs"
  GA_ID: "UA-124648763-1"
  DOMAIN_NAME: "www.pssgrs.com"
  DOMAIN_NAME_SHORT: "pssgrs.com"

production:
  ADMIN_NAME: "Samuel"
  ADMIN_EMAIL: "bouaroua.samuel@gmail.com"
  ADMIN_PASSWORD: "821000"
  GMAIL_USERNAME: "bouaroua.samuel@gmail.com"
  EMAIL_USERNAME: "contact@pssgrs.com"
  GMAIL_PASSWORD: "mhesmueigfewbrhm"
  EMAIL_PASSWORD: "lapapayeverte46*"
  GMAPS_API_KEY: "AIzaSyA14-TBCewFE3UdUPTJH2TusmXe7WHmqzE"
  GMAPSJS_API_KEY: "AIzaSyAKAFuT0h_vdXCvwnufIlETAa57FlNi9Pk"
  AWS_ACCESS_KEY_ID: "AKIAIQHL7MWX4WWKECWA"
  AWS_SECRET_ACCESS_KEY: "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"
  S3_BUCKET: "lespassagers"
  S3_REGION: "eu-west-1"
  FB_APPID: "2709710669054884"
  TW_APPID: "@pssgrs"
  GA_ID: "UA-124648763-1"
  DOMAIN_NAME: "www.pssgrs.com"
  DOMAIN_NAME_SHORT: "pssgrs.com"
