# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

development:
  GMAIL_USERNAME: "bouaroua.samuel@gmail.com"
  GMAIL_PASSWORD: "jcinrwyelnhtvkwc"
  GMAPS_API_KEY: "AIzaSyCJIVW2xEGdMhhNNBnwoSAtzehRpbaSMMg"
  AWS_ACCESS_KEY_ID: "AKIAIQJDWKDMLK75S43Q"
  AWS_SECRET_ACCESS_KEY: "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"
  S3_BUCKET: "lespassagers"
  S3_REGION: "eu-west-1"
  DOMAIN_NAME: "pssgrs.com"

production:
  GMAIL_USERNAME: "bouaroua.samuel@gmail.com"
  GMAIL_PASSWORD: "jcinrwyelnhtvkwc"
  GMAPS_API_KEY: "AIzaSyCJIVW2xEGdMhhNNBnwoSAtzehRpbaSMMg"
  AWS_ACCESS_KEY_ID: "AKIAIQJDWKDMLK75S43Q"
  AWS_SECRET_ACCESS_KEY: "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"
  S3_BUCKET: "lespassagers"
  S3_REGION: "eu-west-1"
  DOMAIN_NAME: "pssgrs.com"
