default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pssgrs_development

test:
  <<: *default
  database: pssgrs_test

production:
  <<: *default
  database: pssgrs_production
  username: pssgrs
